### Exception Handling in Python


```python
# try, except, else, finally

# General exception
try:
    f = open('hjkhd.txt')
except Exception: # Exceptio is a general and vague exception
    print("Sorry no such file available")
```

    Sorry no such file available



```python
# using multiple except
try:
    var = bad_var
    f = open('hjkhd.txt')
except FileNotFoundError: # Exceptio is a general and vague exception
    print("Sorry no such file available")
except Exception:
    print("Sorry Something went wrong")
```

    Sorry Something went wrong



```python
# using aliaing to print the exact message
try:
    var = bad_var
    f = open('hjkhd.txt')
except FileNotFoundError as e: # Exceptio is a general and vague exception
    print(e)
except Exception as e:
    print(e)
```

    name 'bad_var' is not defined



```python
# using else to specify what happens when no exception is thrown

try:
    var = "This is a String"
except FileNotFoundError as e: # Exceptio is a general and vague exception
    print(e)
except Exception as e:
    print(e)
else:
    print(var)
```

    This is a String



```python
# finally runs no matter what happens, 
# This is used to do something regardless of if the code was able to run correctly

try:
    var = givverish
except FileNotFoundError as e: # Exceptio is a general and vague exception
    print(e)
except Exception as e:
    print(e)
else:
    print(var)
finally:
    print("Executing Finally...")
```

    name 'givverish' is not defined
    Executing Finally...



```python
# Raising you own exception

try:
    name = "Thanos"
    if name == "Thanos":
        raise Exception
except Exception:
     print("You should not enter this name")   
```

    You should not enter this name



```python

```
